nome = input('Digite seu nome: ')
print(nome)
print('Seu nome em maiúsculo é: {}'.format(nome.upper()))
print('Seu nome em minúsculo é: {}'.format(nome.lower()))
a = len(nome.strip())
print('Seu nome tem ao todo {} letras.'.format(a - nome.count(' ')))
b = nome.split()
c = len(b[0])
print('Seu 1o nome é {} e ele têm {} letras.'.format(b[0], c))
